"""One-time driver: assembles a profile's real settings_template.json from
its component files via settings_builder.build_settings(), then writes it.

Survival Hunter's own settings_template.json predates settings_builder.py and
was never generated by it in production - prove_settings_builder.py only
proves the builder can REPRODUCE that pre-existing file, it doesn't create
one. A brand-new profile (Stage 6.1's Arms Warrior, and any profile after it)
has no such hand-maintained file to diff against - this script is the real
one-time writer for that case.

Usage: python core/build_profile_settings.py <name_realm> <profile_dir>
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import settings_builder  # noqa: E402
import optimizer as opt  # noqa: E402
import gear_config as gc  # noqa: E402
import gem_optimizer  # noqa: E402
import stat_weights  # noqa: E402

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def build(name_realm: str, profile_dir: str) -> dict:
    char_path = os.path.join(REPO_ROOT, "data", "characters", name_realm, "character.json")
    char_data = json.load(open(char_path, encoding="utf-8"))
    c = char_data["character"]

    profile = json.load(open(os.path.join(profile_dir, "profile.json"), encoding="utf-8"))
    class_options = json.load(open(os.path.join(profile_dir, "class_options.json"), encoding="utf-8"))
    consumables = json.load(open(os.path.join(profile_dir, "consumables.json"), encoding="utf-8"))
    overlay = json.load(open(os.path.join(profile_dir, "raid_buffs_overlay.json"), encoding="utf-8"))
    shared = json.load(open(os.path.join(REPO_ROOT, "profiles", "tbc", "_shared", "raid_buffs_received.json"),
                             encoding="utf-8"))

    # Same active-profile-state wiring run_full_sweep_mv.main() does - needed
    # here too since build_owned_config() below calls into gem_optimizer,
    # which fails loud (by design, Stage 6.0) if this is skipped.
    stat_weights.set_active(stat_weights.load(profile_dir))
    gc.set_active_default_gem(profile["primary_gem_id"])
    chase_bonus = json.load(open(os.path.join(profile_dir, "chase_bonus_gems.json"), encoding="utf-8"))
    gem_optimizer.set_active_chase_bonus_ids(set(chase_bonus["item_ids"]))
    raid_buffs_received = {
        "raidBuffs": {**shared["raidBuffs"], **overlay["raidBuffs"]},
        "debuffs": {**shared["debuffs"], **overlay["debuffs"]},
        "partyBuffs": {**shared["partyBuffs"], **overlay["partyBuffs"]},
        "playerBuffs": {**shared["playerBuffs"], **overlay["playerBuffs"]},
    }

    equipment_items = opt.build_owned_config(char_data["equipped"]["items"])
    character = {
        "race": c["race"],
        "equipment": {"items": equipment_items},
        "talents": c["talents"],
        "professions": c["professions"],
    }

    apl_source = profile.get("apl_source")
    if not apl_source:
        raise ValueError(
            f"{profile_dir}/profile.json has no apl_source - this driver only handles the "
            f"TypeAPL case (Stage 6.1's real finding: the .apl.json file's raw content IS "
            f"player.rotation verbatim). A TypeSimple profile needs its rotation hand-built "
            f"instead, like Hunter's own settings_template.json already is."
        )
    apl_path = os.path.join(REPO_ROOT, "sim", "tbc-new", apl_source)
    rotation = json.load(open(apl_path, encoding="utf-8"))

    return settings_builder.build_settings(
        character, profile, raid_buffs_received,
        rotation=rotation, class_options=class_options, consumables=consumables,
    )


if __name__ == "__main__":
    name_realm, profile_dir = sys.argv[1], sys.argv[2]
    settings = build(name_realm, profile_dir)
    out_path = os.path.join(profile_dir, "settings_template.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(settings, f, indent=2)
    print(f"Wrote {out_path}")
