"""One-time driver: assembles a profile's real settings_template.json from
its component files via settings_builder.build_settings(), then writes it.

Survival Hunter's own settings_template.json predates settings_builder.py and
was never generated by it in production - prove_settings_builder.py only
proves the builder can REPRODUCE that pre-existing file, it doesn't create
one. A brand-new profile (Stage 6.1's Arms Warrior, and any profile after it)
has no such hand-maintained file to diff against - this script is the real
one-time writer for that case.

Usage: python core/build_profile_settings.py <name_realm> <profile_dir>
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import settings_builder  # noqa: E402
import optimizer as opt  # noqa: E402
import gear_config as gc  # noqa: E402
import gem_optimizer  # noqa: E402
import stat_weights  # noqa: E402
import time_horizon  # noqa: E402

import repo_root  # noqa: E402
REPO_ROOT = repo_root.REPO_ROOT
USER_DATA_DIR = repo_root.USER_DATA_DIR


def build(name_realm: str, profile_dir: str) -> dict:
    char_path = os.path.join(USER_DATA_DIR, "characters", name_realm, "character.json")
    char_data = repo_root.load_json(char_path)
    c = char_data["character"]

    profile = repo_root.load_json(os.path.join(profile_dir, "profile.json"))
    class_options = repo_root.load_json(os.path.join(profile_dir, "class_options.json"))
    consumables = repo_root.load_json(os.path.join(profile_dir, "consumables.json"))
    overlay = repo_root.load_json(os.path.join(profile_dir, "raid_buffs_overlay.json"))
    shared = repo_root.load_json(os.path.join(REPO_ROOT, "profiles", "tbc", "_shared", "raid_buffs_received.json"))

    # Same active-profile-state wiring run_upgrade_sweep.main() does - needed
    # here too since build_owned_config() below calls into gem_optimizer,
    # which fails loud (by design, Stage 6.0) if this is skipped.
    stat_weights.set_active(stat_weights.load(profile_dir))
    # Real, necessary as of 2026-09-07's phase-legal-gem fix - gem selection now
    # needs the current phase set first. Every profile's own settings_template.json
    # is built/regenerated against real Phase 3 data, so Phase 3 here too.
    time_horizon.set_current_phase(3)
    gc.set_active_default_gem(profile["primary_gem_id"])
    _default_enchants_path = os.path.join(profile_dir, "default_enchants.json")
    default_enchants = (repo_root.load_json(_default_enchants_path)
                         if os.path.exists(_default_enchants_path) else {})
    gc.set_active_default_enchants(default_enchants)
    chase_bonus = repo_root.load_json(os.path.join(profile_dir, "chase_bonus_gems.json"))
    gem_optimizer.set_active_chase_bonus_ids(set(chase_bonus["item_ids"]))
    raid_buffs_received = {
        "raidBuffs": {**shared["raidBuffs"], **overlay["raidBuffs"]},
        "debuffs": {**shared["debuffs"], **overlay["debuffs"]},
        "partyBuffs": {**shared["partyBuffs"], **overlay["partyBuffs"]},
        "playerBuffs": {**shared["playerBuffs"], **overlay["playerBuffs"]},
    }

    known_professions = {p["name"] for p in c["professions"]}
    equipment_items = opt.build_owned_config(char_data["equipped"]["items"], known_professions)
    character = {
        "race": c["race"],
        "equipment": {"items": equipment_items},
        "talents": c["talents"],
        "professions": c["professions"],
    }

    apl_source = profile.get("apl_source")
    if not apl_source:
        raise ValueError(
            f"{profile_dir}/profile.json has no apl_source - this driver only handles the "
            f"TypeAPL case (Stage 6.1's real finding: the .apl.json file's raw content IS "
            f"player.rotation verbatim). A TypeSimple profile needs its rotation hand-built "
            f"instead, like Hunter's own settings_template.json already is."
        )
    apl_path = os.path.join(REPO_ROOT, "sim", "tbc-new", apl_source)
    rotation = repo_root.load_json(apl_path)

    return settings_builder.build_settings(
        character, profile, raid_buffs_received,
        rotation=rotation, class_options=class_options, consumables=consumables,
    )


if __name__ == "__main__":
    name_realm, profile_dir = sys.argv[1], sys.argv[2]
    settings = build(name_realm, profile_dir)
    out_path = os.path.join(profile_dir, "settings_template.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(settings, f, indent=2)
    print(f"Wrote {out_path}")
